// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Authentication.Model;

#nullable disable

namespace TMS.Authentication.Migrations
{
    [DbContext(typeof(TMSDbContext))]
    [Migration("20250505093424_AuthTokensTable")]
    partial class AuthTokensTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TMS")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.Authentication.Model.AuthTokens", b =>
                {
                    b.Property<int?>("AUTHTOKENID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("AUTHTOKENID"));

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EXPIREDAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<int?>("ISREVOKED")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ISSUEDAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("REFRESHTOKEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOKEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOKENTYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("USERAGENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("USERID")
                        .HasColumnType("int");

                    b.Property<string>("USERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AUTHTOKENID");

                    b.ToTable("AUTHTOKEN", "TMS");
                });

            modelBuilder.Entity("TMS.Authentication.Model.Role", b =>
                {
                    b.Property<int?>("ROLEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ROLEID"));

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<string>("ROLEDESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROLENAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.HasKey("ROLEID");

                    b.ToTable("ROLE", "TMS");

                    b.HasData(
                        new
                        {
                            ROLEID = 1,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISDELETED = 0,
                            ROLEDESC = "It has all access right",
                            ROLENAME = "Super Admin",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ROLEID = 2,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISDELETED = 0,
                            ROLEDESC = "It has all access right.",
                            ROLENAME = "Admin",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ROLEID = 3,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISDELETED = 0,
                            ROLEDESC = "Customer access right to see their task and progress and create ticket as well.",
                            ROLENAME = "Customer",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ROLEID = 4,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISDELETED = 0,
                            ROLEDESC = "Developer access right to see their task.",
                            ROLENAME = "Developer",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TMS.Authentication.Model.user", b =>
                {
                    b.Property<int?>("USERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("USERID"));

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DORMANTSTATUS")
                        .HasColumnType("int");

                    b.Property<string>("EMAILID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRSTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("INCORRECTLOGINS")
                        .HasColumnType("int");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<string>("LASTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LOGINTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("MOBILENO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PWD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PWDEXPIRTYDATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ROLEID")
                        .HasColumnType("int");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("USERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("USERID");

                    b.ToTable("USERS", "TMS");

                    b.HasData(
                        new
                        {
                            USERID = 1,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DORMANTSTATUS = 0,
                            EMAILID = "dilshadali.md@navayugainfotech.com",
                            FIRSTNAME = "Dilshad",
                            INCORRECTLOGINS = 0,
                            ISDELETED = 0,
                            LASTNAME = "ANSARI",
                            LOGINTIME = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MOBILENO = "9911859088",
                            PWD = "123",
                            PWDEXPIRTYDATE = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ROLEID = 1,
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            USERNAME = "Dilshad123"
                        },
                        new
                        {
                            USERID = 2,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DORMANTSTATUS = 0,
                            EMAILID = "venkataramana.tilla@navayugainfotech.com",
                            FIRSTNAME = "Venkat",
                            INCORRECTLOGINS = 0,
                            ISDELETED = 0,
                            LASTNAME = "Tilla",
                            LOGINTIME = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MOBILENO = "9911834023",
                            PWD = "123",
                            PWDEXPIRTYDATE = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ROLEID = 2,
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            USERNAME = "Venkat123"
                        },
                        new
                        {
                            USERID = 3,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DORMANTSTATUS = 0,
                            EMAILID = "manohar.panjala@navayugainfotech.com",
                            FIRSTNAME = "Venkat",
                            INCORRECTLOGINS = 0,
                            ISDELETED = 0,
                            LASTNAME = "Tilla",
                            LOGINTIME = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MOBILENO = "9911675433",
                            PWD = "123",
                            PWDEXPIRTYDATE = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ROLEID = 3,
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            USERNAME = "Manu123"
                        },
                        new
                        {
                            USERID = 4,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DORMANTSTATUS = 0,
                            EMAILID = "karunababu.kondisetti@navayugainfotech.com",
                            FIRSTNAME = "Karuna",
                            INCORRECTLOGINS = 0,
                            ISDELETED = 0,
                            LASTNAME = "Babu",
                            LOGINTIME = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MOBILENO = "9911834023",
                            PWD = "123",
                            PWDEXPIRTYDATE = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ROLEID = 4,
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            USERNAME = "Venkat123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
