// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.DATA.Model;

#nullable disable

namespace TMS.DATA.Migrations
{
    [DbContext(typeof(TMSDbContext))]
    [Migration("20250529075133_EmailData")]
    partial class EmailData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TMS")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.DATA.Model.MailData", b =>
                {
                    b.Property<int?>("MailDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MailDataId"));

                    b.Property<string>("Bodycontent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodycontentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("CcRecipientemailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromemailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ISMigrate")
                        .HasColumnType("int");

                    b.Property<string>("SenderemailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToRecipientemailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.HasKey("MailDataId");

                    b.ToTable("MAILDATA", "TMS");
                });
#pragma warning restore 612, 618
        }
    }
}
