// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.DATA.Model;

#nullable disable

namespace TMS.DATA.Migrations
{
    [DbContext(typeof(TMSDbContext))]
    partial class TMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TMS")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

              modelBuilder.Entity("TMS.DATA.Model.MailData", b =>
                {
                    b.Property<int?>("MailDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MailDataId"));

                    b.Property<string>("MsgId")
                     .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bodycontent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodycontentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("CcRecipientemailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromemailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ISMigrate")
                        .HasColumnType("int");

                    b.Property<string>("SenderemailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToRecipientemailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.HasKey("MailDataId");

                    b.ToTable("MAILDATA", "TMS");
                });



              modelBuilder.Entity("TMS.DATA.Model.MailAttachment", b =>
                {

                    b.Property<int?>("MailAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MailAttachmentId"));

                    b.Property<string>("MsgId")
                        .HasColumnType("nvarchar(max)");
                 
                    b.Property<string>("URL")
                    .HasColumnType("nvarchar(max)");

                    //b.Property<string>("ContentType")
                    //    .HasColumnType("nvarchar(max)");

                    //b.Property<string>("ContentBytes")
                    // .HasColumnType("nvarchar(max)");

                    //b.Property<int>("Size")
                    // .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.HasKey("MailAttachmentId");

                    b.ToTable("MAILATTACHMENT", "TMS");
                });
#pragma warning restore 612, 618
        }
    }
}
