// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Services.Model;

#nullable disable

namespace TMS.Services.Migrations
{
    [DbContext(typeof(TMSDbContext))]
    [Migration("20250502090158_AddProjectTable")]
    partial class AddProjectTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TMS")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.Services.Model.Comment", b =>
                {
                    b.Property<int?>("COMMENTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("COMMENTID"));

                    b.Property<string>("COMMENTTEXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<int?>("TASKID")
                        .HasColumnType("int");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.Property<int?>("USERID")
                        .HasColumnType("int");

                    b.HasKey("COMMENTID");

                    b.ToTable("COMMENTS", "TMS");
                });

            modelBuilder.Entity("TMS.Services.Model.Document", b =>
                {
                    b.Property<int?>("DOCUMENTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("DOCUMENTID"));

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOCUMENTURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<int?>("PROJECTID")
                        .HasColumnType("int");

                    b.Property<int?>("TASKID")
                        .HasColumnType("int");

                    b.Property<int?>("TASKSSTATUSID")
                        .HasColumnType("int");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.HasKey("DOCUMENTID");

                    b.ToTable("DOCUMENTS", "TMS");
                });

            modelBuilder.Entity("TMS.Services.Model.Project", b =>
                {
                    b.Property<int?>("PROJECTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PROJECTID"));

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ENDDATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<string>("PROJECTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("STARTDATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.HasKey("PROJECTID");

                    b.ToTable("PROJECTS", "TMS");
                });

            modelBuilder.Entity("TMS.Services.Model.STATUS", b =>
                {
                    b.Property<int?>("STATUSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("STATUSID"));

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.HasKey("STATUSID");

                    b.ToTable("STATUS", "TMS");

                    b.HasData(
                        new
                        {
                            STATUSID = 1,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "This task is new",
                            ISDELETED = 0,
                            NAME = "New",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            STATUSID = 2,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "This task is in Progress.",
                            ISDELETED = 0,
                            NAME = "In Progress",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            STATUSID = 3,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "This task resolved in Developement Environment",
                            ISDELETED = 0,
                            NAME = "Resolved",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            STATUSID = 4,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "This task already Closed.",
                            ISDELETED = 0,
                            NAME = "Closed",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TMS.Services.Model.TASKCATEGORY", b =>
                {
                    b.Property<int?>("TASKCATEGORYID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TASKCATEGORYID"));

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.HasKey("TASKCATEGORYID");

                    b.ToTable("TASKCATEGORY", "TMS");

                    b.HasData(
                        new
                        {
                            TASKCATEGORYID = 1,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "A flaw in the software or system that causes incorrect or unexpected behavior",
                            ISDELETED = 0,
                            NAME = "Bug / Defect",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKCATEGORYID = 2,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "A suggestion to add new functionality or improve existing features.",
                            ISDELETED = 0,
                            NAME = "Feature Request",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKCATEGORYID = 3,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "Help with resolving technical problems, including hardware, software, or network issues",
                            ISDELETED = 0,
                            NAME = "Technical Support",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKCATEGORYID = 4,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "A formal request for something standard (e.g., access, install, information).",
                            ISDELETED = 0,
                            NAME = "Service Request",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKCATEGORYID = 5,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "A formal request for something standard (e.g., access, install, information).",
                            ISDELETED = 0,
                            NAME = "Service Request",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKCATEGORYID = 6,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "An unplanned interruption to a service or a reduction in service quality.",
                            ISDELETED = 0,
                            NAME = "Incident",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKCATEGORYID = 7,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "User cannot access a system, file, or application.",
                            ISDELETED = 0,
                            NAME = "Access / Permission Issue",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKCATEGORYID = 8,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "Login problems, password resets, locked accounts.",
                            ISDELETED = 0,
                            NAME = "Account Issues",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKCATEGORYID = 9,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "System/application is slow or unresponsive.",
                            ISDELETED = 0,
                            NAME = "Performance Issue",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKCATEGORYID = 10,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "Non-critical feedback about the interface or usability.",
                            ISDELETED = 0,
                            NAME = "UI / UX Feedback",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TMS.Services.Model.TASKSPRIORITY", b =>
                {
                    b.Property<int?>("TASKSPRIORITYID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TASKSPRIORITYID"));

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.HasKey("TASKSPRIORITYID");

                    b.ToTable("TASKSPRIORITY", "TMS");

                    b.HasData(
                        new
                        {
                            TASKSPRIORITYID = 1,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "Low Priority",
                            ISDELETED = 0,
                            NAME = "LOW",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKSPRIORITYID = 2,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "Medium Priority.",
                            ISDELETED = 0,
                            NAME = "Medium",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKSPRIORITYID = 3,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "High Priority",
                            ISDELETED = 0,
                            NAME = "Hign",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TASKSPRIORITYID = 4,
                            CREATEDBY = 1,
                            CREATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DESCRIPTION = "Critical  Priority.",
                            ISDELETED = 0,
                            NAME = "Critical",
                            UPDATEDBY = 1,
                            UPDATEDON = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TMS.Services.Model.Tassk", b =>
                {
                    b.Property<int?>("TASKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TASKID"));

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DUEDATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<int?>("PROJECTID")
                        .HasColumnType("int");

                    b.Property<int?>("TASKCATEGORYID")
                        .HasColumnType("int");

                    b.Property<int?>("TASKSPRIORITYID")
                        .HasColumnType("int");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.Property<int?>("USERID")
                        .HasColumnType("int");

                    b.HasKey("TASKID");

                    b.ToTable("TASKS", "TMS");
                });

            modelBuilder.Entity("TMS.Services.Model.TasskStatus", b =>
                {
                    b.Property<int?>("TASKSSTATUSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TASKSSTATUSID"));

                    b.Property<int?>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ISDELETED")
                        .HasColumnType("int");

                    b.Property<int?>("STATUSID")
                        .HasColumnType("int");

                    b.Property<int?>("TASKCATEGORYID")
                        .HasColumnType("int");

                    b.Property<int?>("TASKPRIORITYID")
                        .HasColumnType("int");

                    b.Property<int?>("UPDATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATEDON")
                        .HasColumnType("datetime2");

                    b.HasKey("TASKSSTATUSID");

                    b.ToTable("TASKSTATUS", "TMS");
                });
#pragma warning restore 612, 618
        }
    }
}
